version: "3.5"
services:
  db:
    build:
      context: ./postgresql
      dockerfile:  Dockerfile
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tbot
      - POSTGRES_DB=postgres
    

volumes:
    db_data: